/**
 * Generate the HTML for the Spire chat webview.
 * Extracted from sidebar.ts to keep UI concerns separate.
 */
export function getChatHtml(): string {
  let s = '';
  s += '<!DOCTYPE html>\n';
  s += '<html>\n';
  s += '<head>\n';
  s += '<meta charset="UTF-8">\n';
  s += '<meta http-equiv="Content-Security-Policy" content="default-src \'none\'; script-src \'unsafe-inline\'; style-src \'unsafe-inline\'; img-src data:;">\n';
  s += '<title>Spire</title>\n';
  s += '<style>\n';
  s += '* { box-sizing: border-box; margin: 0; padding: 0; }\n';
  s += 'body { font-family: var(--vscode-font-family); color: var(--vscode-editor-foreground); background: var(--vscode-sideBar-background); height: 100vh; display: flex; flex-direction: column; padding: 8px; overflow: hidden; }\n';
  s += '.header { display: flex; justify-content: space-between; align-items: center; padding-bottom: 6px; border-bottom: 1px solid var(--vscode-panel-border); flex-shrink: 0; }\n';
  s += '.logo { font-size: 16px; font-weight: 700; display: inline-block; background: #21262d; color: #8b949e; padding: 2px 8px; border-radius: 4px; }\n';
  s += '.toolbar { display: flex; gap: 4px; padding: 4px 0; border-bottom: 1px solid var(--vscode-panel-border); margin-bottom: 4px; flex-shrink: 0; flex-wrap: wrap; }\n';
  s += '.toolbar button { background: transparent; color: var(--vscode-descriptionForeground); border: none; border-radius: 4px; padding: 2px 8px; font-size: 11px; cursor: pointer; display: flex; align-items: center; gap: 3px; }\n';
  s += '.toolbar button:hover { background: var(--vscode-toolbar-hoverBackground); color: var(--vscode-editor-foreground); }\n';
  s += '.toolbar .spacer { flex: 1; }\n';
  s += '.toolbar .clear-btn { color: var(--vscode-errorForeground); }\n';
  s += '.chat-container { flex: 1; overflow-y: auto; padding: 4px 0; display: flex; flex-direction: column; gap: 4px; min-height: 0; }\n';
  s += '.message { width: calc(100% - 12px); margin: 0 6px; padding: 6px 10px; border-radius: 6px; font-size: 13px; line-height: 1.4; word-wrap: break-word; flex-shrink: 0; }\n';
  s += '.message.user { background: transparent; color: inherit; border: 1px solid #1f6feb; padding: 0; display: flex; flex-direction: column; }\n';
  s += '.message.assistant { background: var(--vscode-input-background); border: 1px solid #238636; padding: 0; display: flex; flex-direction: column; }\n';
  s += '.message .label { font-size: 10px; font-weight: 600; opacity: 0.6; display: block; margin-bottom: 2px; }\n';
  s += '.msg-header { background: #238636; color: #000; font-size: 11px; font-weight: 700; padding: 3px 10px; text-transform: uppercase; letter-spacing: 0.5px; flex-shrink: 0; }\n';
  s += '.msg-header-user { background: #1f6feb; color: #000; font-size: 11px; font-weight: 700; padding: 3px 10px; text-transform: uppercase; letter-spacing: 0.5px; flex-shrink: 0; }\n';
  s += '.msg-body { padding: 6px 10px; }\n';
  s += '.input-area { display: flex; gap: 6px; padding: 6px 0 0; border-top: 1px solid var(--vscode-panel-border); flex-shrink: 0; }\n';
  s += '.input-area textarea { flex: 1; background: var(--vscode-input-background); color: var(--vscode-input-foreground); border: 1px solid #f0883e; border-radius: 4px; padding: 6px 8px; font-size: 13px; font-family: var(--vscode-font-family); resize: none; outline: none; min-height: 48px; max-height: 80px; line-height: 1.4; }\n';
  s += '.input-area textarea:focus { border-color: #f0a050; }\n';
  s += '.input-area button { background: var(--vscode-button-background); color: var(--vscode-button-foreground); border: none; border-radius: 4px; padding: 6px 14px; font-size: 13px; cursor: pointer; flex-shrink: 0; align-self: flex-start; }\n';
  s += '.input-area button:hover { background: var(--vscode-button-hoverBackground); }\n';
  s += '.input-area button:disabled { opacity: 0.5; cursor: not-allowed; }\n';
  s += '.error-message { color: var(--vscode-errorForeground); background: var(--vscode-inputValidation-errorBackground); padding: 6px 10px; border-radius: 4px; margin: 4px 0; font-size: 13px; }\n';
  s += '.status-bar { font-size: 11px; color: var(--vscode-descriptionForeground); padding: 4px 0; border-top: 1px solid var(--vscode-panel-border); margin-top: 4px; flex-shrink: 0; text-align: center; }\n';
  s += '.thinking { display: flex; align-items: center; gap: 8px; padding: 8px 10px; font-size: 13px; color: var(--vscode-descriptionForeground); font-style: italic; animation: think-pulse 1.2s ease-in-out infinite; }\n';
  s += '.thinking .dots::after { content: ""; animation: think-dots 1.5s steps(4, end) infinite; }\n';
  s += '@keyframes think-pulse { 0%, 100% { opacity: 0.6; } 50% { opacity: 1; } }\n';
  s += '@keyframes think-dots { 0% { content: ""; } 25% { content: "."; } 50% { content: ".."; } 75% { content: "..."; } 100% { content: ""; } }\n';
  // Reasoning bubble styles — visible for DeepSeek V4 thinking blocks
  s += '.reasoning-bubble { background: var(--vscode-editorWidget-background, #1e1e1e); border: 1px solid var(--vscode-panel-border, #404040); border-left: 3px solid #f0a050; border-radius: 4px; padding: 6px 10px; margin: 4px 10px 2px 10px; font-size: 12px; color: var(--vscode-descriptionForeground, #8b949e); max-height: 200px; overflow-y: auto; white-space: pre-wrap; word-wrap: break-word; display: none; }\n';
  s += '.reasoning-bubble.visible { display: block; }\n';
  s += '.reasoning-header { font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; color: #f0a050; margin-bottom: 3px; cursor: pointer; user-select: none; }\n';
  s += '.reasoning-header:hover { opacity: 0.8; }\n';
  // Markdown-rendered content styles
  s += '.msg-body h1, .msg-body h2, .msg-body h3, .msg-body h4, .msg-body h5, .msg-body h6 { margin: 8px 0 4px 0; font-weight: 600; line-height: 1.3; }\n';
  s += '.msg-body h1 { font-size: 18px; border-bottom: 1px solid var(--vscode-panel-border); padding-bottom: 4px; }\n';
  s += '.msg-body h2 { font-size: 16px; border-bottom: 1px solid var(--vscode-panel-border); padding-bottom: 3px; }\n';
  s += '.msg-body h3 { font-size: 15px; }\n';
  s += '.msg-body h4 { font-size: 14px; }\n';
  s += '.msg-body p { margin: 4px 0; }\n';
  s += '.msg-body ul, .msg-body ol { margin: 4px 0; padding-left: 22px; }\n';
  s += '.msg-body li { margin: 2px 0; }\n';
  s += '.msg-body blockquote { margin: 6px 0; padding: 4px 10px; border-left: 3px solid #f0883e; color: var(--vscode-descriptionForeground); font-style: italic; }\n';
  s += '.msg-body pre { margin: 8px 0; padding: 10px; background: var(--vscode-textCodeBlock-background, #1e1e1e); border: 1px solid var(--vscode-panel-border); border-radius: 4px; overflow-x: auto; }\n';
  s += '.msg-body code { font-family: var(--vscode-editor-font-family, "Cascadia Code", "Fira Code", monospace); font-size: 12px; }\n';
  s += '.msg-body pre code { background: none; padding: 0; border: none; }\n';
  s += '.msg-body :not(pre) > code { background: var(--vscode-textCodeBlock-background, #1e1e1e); padding: 1px 4px; border-radius: 3px; border: 1px solid var(--vscode-panel-border); }\n';
  s += '.msg-body table { border-collapse: collapse; margin: 8px 0; width: 100%; font-size: 12px; }\n';
  s += '.msg-body th, .msg-body td { border: 1px solid var(--vscode-panel-border); padding: 4px 8px; text-align: left; }\n';
  s += '.msg-body th { background: var(--vscode-sideBarSectionHeader-background, #2d2d2d); font-weight: 600; }\n';
  s += '.msg-body tr:nth-child(even) { background: var(--vscode-list-hoverBackground, #2a2d2e); }\n';
  s += '.msg-body hr { border: none; border-top: 1px solid var(--vscode-panel-border); margin: 10px 0; }\n';
  s += '.msg-body img { max-width: 100%; border-radius: 4px; margin: 4px 0; }\n';
  s += '.msg-body a { color: var(--vscode-textLink-foreground, #58a6ff); text-decoration: underline; }\n';
  s += '.msg-body a:hover { color: var(--vscode-textLink-activeForeground, #79c0ff); }\n';
  s += '</style>\n';
  s += '</head>\n';
  s += '<body>\n';
  s += '<div class="header"><span class="logo">⛰️ Spire</span></div>\n';
  s += '<div class="toolbar">\n';
  s += '<button id="setApiKeyBtn">🔑 Key</button>\n';
  s += '<button id="initMemoryBtn">📁 Memory</button>\n';
  s += '<button id="loadContextBtn">📂 Context</button>\n';
  s += '<span class="spacer"></span>\n';
  s += '<button id="clearBtn" class="clear-btn">🗑️ Clear</button>\n';
  s += '</div>\n';
  s += '<div class="chat-container" id="chatContainer"></div>\n';
  s += '<div class="input-area">\n';
  s += '<textarea id="userInput" rows="2" placeholder="Ask Spire..." spellcheck="false"></textarea>\n';
  s += '<button id="sendBtn">Send</button>\n';
  s += '</div>\n';
  s += '<div class="status-bar" id="statusBar">Ready</div>\n';
  s += '<script>\n';
  s += '"use strict";\n';
  s += '(function(){\n';
  s += '  var vs = null;\n';
  s += '  try { vs = acquireVsCodeApi(); } catch(e){}\n';
  s += '  if (!vs) { document.getElementById("statusBar").textContent = "NO VSCODE API"; return; }\n';
  s += '  var chat = document.getElementById("chatContainer");\n';
  s += '  var input = document.getElementById("userInput");\n';
  s += '  var sendBtn = document.getElementById("sendBtn");\n';
  s += '  var statusBar = document.getElementById("statusBar");\n';
  s += '  function isNearBottom(el) { return el.scrollHeight - el.scrollTop - el.clientHeight < 60; }\n';
  s += '  function scrollToBottom(el) { if (isNearBottom(el)) { el.scrollTop = el.scrollHeight; } }\n';
  s += '  function addUserMsg(text) {\n';
  s += '    var d = document.createElement("div");\n';
  s += '    d.className = "message user";\n';
  s += '    var h = document.createElement("div");\n';
  s += '    h.className = "msg-header-user";\n';
  s += '    h.textContent = "YOU";\n';
  s += '    d.appendChild(h);\n';
  s += '    var b = document.createElement("div");\n';
  s += '    b.className = "msg-body";\n';
  s += '    b.innerHTML = (text || "").replace(/\\n/g, "<br>");\n';
  s += '    d.appendChild(b);\n';
  s += '    chat.appendChild(d);\n';
  s += '    scrollToBottom(chat);\n';
  s += '  }\n';
  s += '  function addErr(text) {\n';
  s += '    var d = document.createElement("div");\n';
  s += '    d.className = "error-message";\n';
  s += '    d.textContent = text;\n';
  s += '    chat.appendChild(d);\n';
  s += '    scrollToBottom(chat);\n';
  s += '  }\n';
  s += '  sendBtn.addEventListener("click", function() {\n';
  s += '    var text = input.value.trim();\n';
  s += '    if (!text) return;\n';
  s += '    input.value = "";\n';
  s += '    addUserMsg(text);\n';
  s += '    showThinking();\n';
  s += '    statusBar.textContent = "Sending...";\n';
  s += '    vs.postMessage({ type: "ask", content: text });\n';
  s += '  });\n';
  s += '  input.addEventListener("keydown", function(e) {\n';
  s += '    if (e.key === "Enter" && !e.shiftKey) {\n';
  s += '      e.preventDefault();\n';
  s += '      sendBtn.click();\n';
  s += '    }\n';
  s += '  });\n';
  s += '  document.getElementById("clearBtn").addEventListener("click", function() {\n';
  s += '    hideThinking();\n';
  s += '    chat.innerHTML = "";\n';
  s += '    statusBar.textContent = "Cleared";\n';
  s += '    vs.postMessage({ type: "clear" });\n';
  s += '  });\n';
  s += '  document.getElementById("setApiKeyBtn").addEventListener("click", function() {\n';
  s += '    vs.postMessage({ type: "setApiKey" });\n';
  s += '  });\n';
  s += '  document.getElementById("initMemoryBtn").addEventListener("click", function() {\n';
  s += '    vs.postMessage({ type: "initMemoryBank" });\n';
  s += '    statusBar.textContent = "Initializing memory bank...";\n';
  s += '  });\n';
  s += '  document.getElementById("loadContextBtn").addEventListener("click", function() {\n';
  s += '    vs.postMessage({ type: "loadContext" });\n';
  s += '    statusBar.textContent = "Loading context...";\n';
  s += '  });\n';
  s += '  var thinkingEl = null;\n';
  s += '  function showThinking() {\n';
  s += '    if (thinkingEl) return;\n';
  s += '    var d = document.createElement("div");\n';
  s += '    d.className = "message assistant";\n';
  s += '    var t = document.createElement("div");\n';
  s += '    t.className = "thinking";\n';
  s += '    t.innerHTML = "⏳ Spire is thinking<span class=\\"dots\\"></span>";\n';
  s += '    d.appendChild(t);\n';
  s += '    chat.appendChild(d);\n';
  s += '    thinkingEl = d;\n';
  s += '    scrollToBottom(chat);\n';
  s += '  }\n';
  s += '  function hideThinking() {\n';
  s += '    if (thinkingEl) {\n';
  s += '      thinkingEl.remove();\n';
  s += '      thinkingEl = null;\n';
  s += '    }\n';
  s += '  }\n';
  s += '  // addAssistantMsg with optional reasoning bubble for DeepSeek V4 thinking blocks\n';
  s += '  function addAssistantMsg(content, reasoning) {\n';
  s += '    var d = document.createElement("div");\n';
  s += '    d.className = "message assistant";\n';
  s += '    var h = document.createElement("div");\n';
  s += '    h.className = "msg-header";\n';
  s += '    h.textContent = "SPIRE";\n';
  s += '    d.appendChild(h);\n';
  s += '    if (reasoning) {\n';
  s += '      var r = document.createElement("div");\n';
  s += '      r.className = "reasoning-bubble visible";\n';
  s += '      var rh = document.createElement("div");\n';
  s += '      rh.className = "reasoning-header";\n';
  s += '      rh.textContent = "🧠 Reasoning (click to toggle)";\n';
  s += '      rh.addEventListener("click", function() {\n';
  s += '        r.classList.toggle("visible");\n';
  s += '      });\n';
  s += '      r.appendChild(rh);\n';
  s += '      var rb = document.createElement("div");\n';
  s += '      rb.textContent = reasoning;\n';
  s += '      r.appendChild(rb);\n';
  s += '      d.appendChild(r);\n';
  s += '    }\n';
  s += '    var b = document.createElement("div");\n';
  s += '    b.className = "msg-body";\n';
  s += '    b.innerHTML = content || "";\n';
  s += '    d.appendChild(b);\n';
  s += '    chat.appendChild(d);\n';
  s += '    scrollToBottom(chat);\n';
  s += '  }\n';
  s += '  window.addEventListener("message", function(event) {\n';
  s += '    var msg = event.data;\n';
  s += '    if (msg.type === "response") {\n';
  s += '      hideThinking();\n';
  s += '      addAssistantMsg(msg.content, msg.reasoning);\n';
  s += '      statusBar.textContent = "Ready";\n';
  s += '    } else if (msg.type === "error") {\n';
  s += '      hideThinking();\n';
  s += '      addErr(msg.content || "Unknown error");\n';
  s += '      statusBar.textContent = "Error";\n';
  s += '    } else if (msg.type === "contextLoaded") {\n';
  s += '      hideThinking();\n';
  s += '      addAssistantMsg(msg.content);\n';
  s += '      statusBar.textContent = "Ready";\n';
  s += '    } else if (msg.type === "cleared") {\n';
  s += '      statusBar.textContent = "Ready";\n';
  s += '    } else if (msg.type === "restoreConversation") {\n';
  s += '      var msgs = msg.messages || [];\n';
  s += '      for (var i = 0; i < msgs.length; i++) {\n';
  s += '        if (msgs[i].role === "user") {\n';
  s += '          addUserMsg(msgs[i].content);\n';
  s += '        } else if (msgs[i].role === "assistant") {\n';
  s += '          addAssistantMsg(msgs[i].content);\n';
  s += '        }\n';
  s += '      }\n';
  s += '      statusBar.textContent = "Ready";\n';
  s += '    }\n';
  s += '  });\n';
  s += '  vs.postMessage({ type: "ready" });\n';
  s += '})();\n';
  s += '</script>\n';
  s += '</body>\n';
  s += '</html>\n';
  return s;
}
