import { getMcpCss } from './mcp-html';

/**
 * Generate the HTML for the unified Spire sidebar webview.
 */
export function getSidebarHtml(): string {
  let s = '';
  s += '<!DOCTYPE html>\n';
  s += '<html>\n';
  s += '<head>\n';
  s += '<meta charset="UTF-8">\n';
  s += '<meta http-equiv="Content-Security-Policy" content="default-src \'none\'; script-src \'unsafe-inline\'; style-src \'unsafe-inline\'; img-src data:;">\n';
  s += '<title>Spire</title>\n';
  s += '<style>\n';
  
  // Shared resets and container
  s += '* { box-sizing: border-box; margin: 0; padding: 0; }\n';
  s += 'body { font-family: var(--vscode-font-family); color: var(--vscode-editor-foreground); background: var(--vscode-sideBar-background); height: 100vh; display: flex; flex-direction: column; overflow: hidden; }\n';
  
  // Tab Bar Styles
  s += '.tab-bar { display: flex; border-bottom: 1px solid var(--vscode-panel-border); background: var(--vscode-sideBar-background); flex-shrink: 0; }\n';
  s += '.tab-btn { flex: 1; padding: 8px 0; border: none; background: transparent; color: var(--vscode-descriptionForeground); font-size: 12px; cursor: pointer; text-align: center; border-bottom: 2px solid transparent; transition: color 0.2s, border-color 0.2s; }\n';
  s += '.tab-btn:hover { color: var(--vscode-editor-foreground); }\n';
  s += '.tab-btn.active { color: var(--vscode-editor-foreground); border-bottom-color: var(--vscode-button-background); }\n';
  
  // Tab Content Container
  s += '.tab-content { display: none; flex: 1; flex-direction: column; overflow: hidden; padding: 8px; }\n';
  s += '.tab-content.active { display: flex; }\n';
  
  // --- Prompt (Chat) Styles ---
  s += '.header { display: flex; justify-content: space-between; align-items: center; padding-bottom: 6px; border-bottom: 1px solid var(--vscode-panel-border); flex-shrink: 0; }\n';
  s += '.logo { font-size: 16px; font-weight: 700; display: inline-block; background: #21262d; color: #8b949e; padding: 2px 8px; border-radius: 4px; }\n';
  s += '.toolbar { display: flex; gap: 4px; padding: 4px 0; border-bottom: 1px solid var(--vscode-panel-border); margin-bottom: 4px; flex-shrink: 0; flex-wrap: wrap; }\n';
  s += '.toolbar button { background: transparent; color: var(--vscode-descriptionForeground); border: none; border-radius: 4px; padding: 2px 8px; font-size: 11px; cursor: pointer; display: flex; align-items: center; gap: 3px; }\n';
  s += '.toolbar button:hover { background: var(--vscode-toolbar-hoverBackground); color: var(--vscode-editor-foreground); }\n';
  s += '.toolbar .spacer { flex: 1; }\n';
  s += '.toolbar .clear-btn { color: var(--vscode-errorForeground); }\n';
  s += '.chat-container { flex: 1; overflow-y: auto; padding: 4px 0; display: flex; flex-direction: column; gap: 4px; min-height: 0; }\n';
  s += '.message { width: calc(100% - 12px); margin: 0 6px; padding: 6px 10px; border-radius: 6px; font-size: 13px; line-height: 1.4; word-wrap: break-word; flex-shrink: 0; }\n';
  s += '.message.user { background: transparent; color: inherit; border: 1px solid #1f6feb; padding: 0; display: flex; flex-direction: column; }\n';
  s += '.message.assistant { background: var(--vscode-input-background); border: 1px solid #238636; padding: 0; display: flex; flex-direction: column; }\n';
  s += '.message .label { font-size: 10px; font-weight: 600; opacity: 0.6; display: block; margin-bottom: 2px; }\n';
  s += '.msg-header { background: #238636; color: #000; font-size: 11px; font-weight: 700; padding: 3px 10px; text-transform: uppercase; letter-spacing: 0.5px; flex-shrink: 0; }\n';
  s += '.msg-header-user { background: #1f6feb; color: #000; font-size: 11px; font-weight: 700; padding: 3px 10px; text-transform: uppercase; letter-spacing: 0.5px; flex-shrink: 0; }\n';
  s += '.msg-body { padding: 6px 10px; }\n';
  s += '.input-area { display: flex; gap: 6px; padding: 6px 0 0; border-top: 1px solid var(--vscode-panel-border); flex-shrink: 0; }\n';
  s += '.input-area textarea { flex: 1; background: var(--vscode-input-background); color: var(--vscode-input-foreground); border: 1px solid #f0883e; border-radius: 4px; padding: 6px 8px; font-size: 13px; font-family: var(--vscode-font-family); resize: none; outline: none; min-height: 48px; max-height: 80px; line-height: 1.4; }\n';
  s += '.input-area textarea:focus { border-color: #f0a050; }\n';
  s += '.input-area button { background: var(--vscode-button-background); color: var(--vscode-button-foreground); border: none; border-radius: 4px; padding: 6px 14px; font-size: 13px; cursor: pointer; flex-shrink: 0; align-self: flex-start; }\n';
  s += '.input-area button:hover { background: var(--vscode-button-hoverBackground); }\n';
  s += '.input-area button:disabled { opacity: 0.5; cursor: not-allowed; }\n';
  s += '.error-message { color: var(--vscode-errorForeground); background: var(--vscode-inputValidation-errorBackground); padding: 6px 10px; border-radius: 4px; margin: 4px 0; font-size: 13px; }\n';
  s += '.status-bar { font-size: 11px; color: var(--vscode-descriptionForeground); padding: 4px 0; border-top: 1px solid var(--vscode-panel-border); margin-top: 4px; flex-shrink: 0; text-align: center; }\n';
  s += '.thinking { display: flex; align-items: center; gap: 8px; padding: 8px 10px; font-size: 13px; color: var(--vscode-descriptionForeground); font-style: italic; animation: think-pulse 1.2s ease-in-out infinite; }\n';
  s += '.thinking .dots::after { content: ""; animation: think-dots 1.5s steps(4, end) infinite; }\n';
  s += '@keyframes think-pulse { 0%, 100% { opacity: 0.6; } 50% { opacity: 1; } }\n';
  s += '@keyframes think-dots { 0% { content: ""; } 25% { content: "."; } 50% { content: ".."; } 75% { content: "..."; } 100% { content: ""; } }\n';
  s += '.reasoning-bubble { background: var(--vscode-editorWidget-background, #1e1e1e); border: 1px solid var(--vscode-panel-border, #404040); border-left: 3px solid #f0a050; border-radius: 4px; padding: 6px 10px; margin: 4px 10px 2px 10px; font-size: 12px; color: var(--vscode-descriptionForeground, #8b949e); max-height: 200px; overflow-y: auto; white-space: pre-wrap; word-wrap: break-word; display: none; }\n';
  s += '.reasoning-bubble.visible { display: block; }\n';
  s += '.reasoning-header { font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; color: #f0a050; margin-bottom: 3px; cursor: pointer; user-select: none; }\n';
  s += '.reasoning-header:hover { opacity: 0.8; }\n';
  s += '.msg-body h1, .msg-body h2, .msg-body h3, .msg-body h4, .msg-body h5, .msg-body h6 { margin: 8px 0 4px 0; font-weight: 600; line-height: 1.3; }\n';
  s += '.msg-body h1 { font-size: 18px; border-bottom: 1px solid var(--vscode-panel-border); padding-bottom: 4px; }\n';
  s += '.msg-body p { margin-bottom: 8px; }\n';
  s += '.msg-body pre { background: var(--vscode-textCodeBlock-background); padding: 8px; border-radius: 4px; overflow-x: auto; margin-bottom: 8px; border: 1px solid var(--vscode-panel-border); }\n';
  s += '.msg-body code { font-family: var(--vscode-editor-font-family); font-size: 12px; }\n';
  s += '.msg-body p > code { background: var(--vscode-textCodeBlock-background); padding: 2px 4px; border-radius: 3px; }\n';
  s += '.msg-body ul, .msg-body ol { margin-bottom: 8px; padding-left: 20px; }\n';
  s += '.msg-body-wrapper { position: relative; }\n';
  s += '.copy-btn { position: absolute; top: 4px; right: 4px; background: var(--vscode-button-background); color: var(--vscode-button-foreground); border: none; border-radius: 3px; width: 24px; height: 24px; cursor: pointer; font-size: 12px; display: flex; align-items: center; justify-content: center; opacity: 0; transition: opacity 0.2s; z-index: 1; }\n';
  s += '.msg-body-wrapper:hover .copy-btn { opacity: 0.8; }\n';
  s += '.copy-btn:hover { opacity: 1 !important; }\n';
  s += '.copy-btn.copied { background: #238636; }\n';
  
  // --- MCP Styles ---
  s += getMcpCss();
  s += '#tab-mcp { overflow-y: auto; }\n';
  
  // --- Graph Tab Styles ---
  s += '.graph-toolbar { display: flex; gap: 4px; padding: 4px 0; border-bottom: 1px solid var(--vscode-panel-border); margin-bottom: 4px; flex-shrink: 0; align-items: center; }\n';
  s += '.graph-toolbar button { background: transparent; color: var(--vscode-descriptionForeground); border: 1px solid var(--vscode-panel-border); border-radius: 4px; padding: 2px 8px; font-size: 11px; cursor: pointer; display: flex; align-items: center; gap: 3px; }\n';
  s += '.graph-toolbar button:hover { background: var(--vscode-toolbar-hoverBackground); color: var(--vscode-editor-foreground); }\n';
  s += '.graph-toolbar input { flex: 1; max-width: 200px; background: var(--vscode-input-background); color: var(--vscode-input-foreground); border: 1px solid var(--vscode-panel-border); border-radius: 4px; padding: 2px 8px; font-size: 11px; outline: none; }\n';
  s += '.graph-toolbar input:focus { border-color: var(--vscode-focusBorder); }\n';
  s += '.graph-toolbar .spacer { flex: 1; }\n';
  s += '.graph-canvas-container { flex: 1; position: relative; overflow: hidden; border: 1px solid var(--vscode-panel-border); border-radius: 4px; background: var(--vscode-editor-background); min-height: 0; }\n';
  s += '.graph-canvas-container svg { display: block; cursor: grab; }\n';
  s += '.graph-canvas-container svg:active { cursor: grabbing; }\n';
  s += '.graph-node { cursor: pointer; transition: opacity 0.2s; }\n';
  s += '.graph-node:hover { filter: brightness(1.3); }\n';
  s += '.graph-node-label { font-size: 10px; fill: var(--vscode-editor-foreground); pointer-events: none; text-anchor: middle; dominant-baseline: central; }\n';
  s += '.graph-edge { stroke: var(--vscode-panel-border); stroke-width: 1; fill: none; }\n';
  s += '.graph-edge-label { font-size: 8px; fill: var(--vscode-descriptionForeground); pointer-events: none; text-anchor: middle; }\n';
  s += '.graph-tooltip { position: absolute; background: var(--vscode-editorWidget-background); border: 1px solid var(--vscode-panel-border); border-radius: 4px; padding: 6px 10px; font-size: 12px; pointer-events: none; z-index: 10; max-width: 250px; box-shadow: 0 2px 8px rgba(0,0,0,0.3); }\n';
  s += '.graph-tooltip .tt-name { font-weight: 600; margin-bottom: 2px; }\n';
  s += '.graph-tooltip .tt-desc { color: var(--vscode-descriptionForeground); font-size: 11px; }\n';
  s += '.graph-tooltip .tt-type { font-size: 10px; color: var(--vscode-descriptionForeground); opacity: 0.7; margin-top: 2px; }\n';
  s += '.graph-legend { display: flex; gap: 8px; padding: 4px 0; flex-shrink: 0; flex-wrap: wrap; font-size: 10px; color: var(--vscode-descriptionForeground); }\n';
  s += '.graph-legend-item { display: flex; align-items: center; gap: 3px; }\n';
  s += '.graph-legend-dot { width: 8px; height: 8px; border-radius: 50%; display: inline-block; }\n';
  s += '.graph-loading { display: flex; align-items: center; justify-content: center; height: 100%; color: var(--vscode-descriptionForeground); font-size: 13px; }\n';
  
  // Node Detail Panel
  s += '.graph-detail-panel { display: none; flex-shrink: 0; max-height: 200px; overflow-y: auto; border: 1px solid var(--vscode-panel-border); border-radius: 4px; background: var(--vscode-editorWidget-background); margin-top: 4px; padding: 8px 10px; font-size: 12px; }\n';
  s += '.graph-detail-panel.visible { display: block; }\n';
  s += '.graph-detail-header { display: flex; align-items: center; gap: 6px; margin-bottom: 6px; padding-bottom: 4px; border-bottom: 1px solid var(--vscode-panel-border); }\n';
  s += '.graph-detail-dot { width: 10px; height: 10px; border-radius: 50%; flex-shrink: 0; }\n';
  s += '.graph-detail-title { font-weight: 600; font-size: 13px; flex: 1; word-break: break-all; }\n';
  s += '.graph-detail-close { background: transparent; color: var(--vscode-descriptionForeground); border: none; cursor: pointer; font-size: 14px; padding: 0 4px; line-height: 1; }\n';
  s += '.graph-detail-close:hover { color: var(--vscode-editor-foreground); }\n';
  s += '.graph-detail-section { margin-bottom: 4px; }\n';
  s += '.graph-detail-label { font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; color: var(--vscode-descriptionForeground); opacity: 0.7; margin-bottom: 2px; }\n';
  s += '.graph-detail-value { color: var(--vscode-editor-foreground); word-break: break-word; }\n';
  s += '.graph-detail-table { width: 100%; border-collapse: collapse; font-size: 11px; }\n';
  s += '.graph-detail-table td { padding: 2px 4px; vertical-align: top; }\n';
  s += '.graph-detail-table td:first-child { font-weight: 600; color: var(--vscode-descriptionForeground); width: 120px; white-space: nowrap; }\n';
  s += '.graph-detail-table td:last-child { color: var(--vscode-editor-foreground); word-break: break-word; }\n';
  s += '.graph-detail-table tr:nth-child(even) { background: var(--vscode-list-hoverBackground); }\n';
  
  s += '</style>\n';
  s += '</head>\n';
  s += '<body>\n';
  
  // Tab Bar
  s += '  <div class="tab-bar">\n';
  s += '    <button class="tab-btn active" data-target="tab-prompt">Prompt</button>\n';
  s += '    <button class="tab-btn" data-target="tab-mcp">MCP</button>\n';
  s += '    <button class="tab-btn" data-target="tab-graph">Graph</button>\n';
  s += '  </div>\n';

  // --- Prompt Tab ---
  s += '  <div id="tab-prompt" class="tab-content active">\n';
  s += '    <div class="header">\n';
  s += '      <div class="logo">⛰️ Spire</div>\n';
  s += '    </div>\n';
  s += '    <div class="toolbar">\n';
  s += '      <button onclick="postMsg(\'setApiKey\')">🔑 Set API Key</button>\n';
  s += '      <button onclick="postMsg(\'initMemoryBank\')">🧠 Init Memory</button>\n';
  s += '      <div class="spacer"></div>\n';
  s += '      <button class="clear-btn" onclick="postMsg(\'clear\')">🗑️ Clear</button>\n';
  s += '    </div>\n';
  s += '    <div class="chat-container" id="chat"></div>\n';
  s += '    <div class="input-area">\n';
  s += '      <textarea id="prompt" placeholder="Ask Spire... (Shift+Enter for newline, Enter to send)" rows="1"></textarea>\n';
  s += '      <button id="send-btn" onclick="submitPrompt()">Send</button>\n';
  s += '    </div>\n';
  s += '    <div class="status-bar" id="status">Ready</div>\n';
  s += '  </div>\n';

  // --- MCP Tab ---
  s += '  <div id="tab-mcp" class="tab-content mcp-container">\n';
  s += '    <div id="mcp-content">Loading MCP dashboard...</div>\n';
  s += '  </div>\n';

  // --- Graph Tab ---
  s += '  <div id="tab-graph" class="tab-content">\n';
  s += '    <div class="graph-toolbar">\n';
  s += '      <button onclick="postMsg(\'graph.refresh\')" title="Refresh graph data">🔄 Refresh</button>\n';
  s += '      <input type="text" id="graph-search" placeholder="Filter nodes..." oninput="filterGraph(this.value)">\n';
  s += '      <span class="spacer"></span>\n';
  s += '      <button onclick="zoomIn()" title="Zoom in">🔍+</button>\n';
  s += '      <button onclick="zoomOut()" title="Zoom out">🔍−</button>\n';
  s += '      <button onclick="resetView()" title="Reset view">⟲ Fit</button>\n';
  s += '    </div>\n';
  s += '    <div class="graph-canvas-container" id="graph-container">\n';
  s += '      <svg id="graph-svg" width="100%" height="100%"></svg>\n';
  s += '      <div id="graph-tooltip" class="graph-tooltip" style="display:none;"></div>\n';
  s += '    </div>\n';
  s += '    <div class="graph-legend" id="graph-legend"></div>\n';
  s += '    <div class="graph-detail-panel" id="graph-detail-panel"></div>\n';
  s += '  </div>\n';

  // --- Scripts ---
  s += '  <script>\n';
  s += '    const vscode = acquireVsCodeApi();\n';
  s += '    const chatEl = document.getElementById("chat");\n';
  s += '    const promptEl = document.getElementById("prompt");\n';
  s += '    const sendBtn = document.getElementById("send-btn");\n';
  s += '    const statusEl = document.getElementById("status");\n';
  s += '    let isWaiting = false;\n';
  
  // Tab Switching Logic
  s += '    const tabBtns = document.querySelectorAll(".tab-btn");\n';
  s += '    const tabContents = document.querySelectorAll(".tab-content");\n';
  s += '    tabBtns.forEach(btn => {\n';
  s += '      btn.addEventListener("click", () => {\n';
  s += '        tabBtns.forEach(b => b.classList.remove("active"));\n';
  s += '        tabContents.forEach(c => c.classList.remove("active"));\n';
  s += '        btn.classList.add("active");\n';
  s += '        document.getElementById(btn.getAttribute("data-target")).classList.add("active");\n';
  s += '        if (btn.getAttribute("data-target") === "tab-mcp") {\n';
  s += '          postMsg("mcp.refresh");\n';
  s += '        }\n';
  s += '      });\n';
  s += '    });\n';
  
  // Universal Post Message
  s += '    function postMsg(type, payload) {\n';
  s += '      vscode.postMessage({ type, content: payload });\n';
  s += '    }\n';

  // Chat specific functions
  s += '    function submitPrompt() {\n';
  s += '      const text = promptEl.value.trim();\n';
  s += '      if (!text || isWaiting) return;\n';
  s += '      appendUserMessage(text);\n';
  s += '      promptEl.value = "";\n';
  s += '      setWaiting(true);\n';
  s += '      postMsg("ask", text);\n';
  s += '    }\n';

  s += '    promptEl.addEventListener("keydown", (e) => {\n';
  s += '      if (e.key === "Enter" && !e.shiftKey) {\n';
  s += '        e.preventDefault();\n';
  s += '        submitPrompt();\n';
  s += '      }\n';
  s += '    });\n';
  
  s += '    let thinkingEl = null;\n';
  s += '    let thinkingBodyEl = null;\n';
  s += '    function setWaiting(waiting) {\n';
  s += '      isWaiting = waiting;\n';
  s += '      sendBtn.disabled = waiting;\n';
  s += '      promptEl.disabled = waiting;\n';
  s += '      if (waiting) {\n';
  s += '        statusEl.innerText = "Thinking...";\n';
  s += '        const div = document.createElement("div");\n';
  s += '        div.className = "message assistant";\n';
  s += '        div.innerHTML = "<div class=\\"msg-header\\">Spire</div><div class=\\"msg-body\\" id=\\"thinking-body\\"><span class=\\"thinking\\">Spire is thinking<span class=\\"dots\\"></span></span></div>";\n';
  s += '        chatEl.appendChild(div);\n';
  s += '        chatEl.scrollTop = chatEl.scrollHeight;\n';
  s += '        thinkingEl = div;\n';
  s += '        thinkingBodyEl = document.getElementById("thinking-body");\n';
  s += '      } else {\n';
  s += '        if (thinkingEl && thinkingEl.parentNode) {\n';
  s += '          thinkingEl.parentNode.removeChild(thinkingEl);\n';
  s += '        }\n';
  s += '        thinkingEl = null;\n';
  s += '        thinkingBodyEl = null;\n';
  s += '        statusEl.innerText = "Ready";\n';
  s += '        setTimeout(() => promptEl.focus(), 100);\n';
  s += '      }\n';
  s += '    }\n';

  s += '    function updateThinkingStatus(status) {\n';
  s += '      if (!thinkingBodyEl) return;\n';
  s += '      if (status.type === "thinking") {\n';
  s += '        thinkingBodyEl.innerHTML = "<span class=\\"thinking\\">Spire is thinking<span class=\\"dots\\"></span></span>";\n';
  s += '        statusEl.innerText = "Thinking...";\n';
  s += '      } else if (status.type === "tool_call") {\n';
  s += '        const toolName = status.toolName || "unknown";\n';
  s += '        thinkingBodyEl.innerHTML = "<span class=\\"thinking\\">Spire is using tool: <code style=\\"background:var(--vscode-textCodeBlock-background);padding:1px 5px;border-radius:3px;font-size:12px;\\">" + escapeHtml(toolName) + "</code><span class=\\"dots\\"></span></span>";\n';
  s += '        statusEl.innerText = "Using tool: " + toolName;\n';
  s += '      }\n';
  s += '      chatEl.scrollTop = chatEl.scrollHeight;\n';
  s += '    }\n';

  s += '    function escapeHtml(unsafe) {\n';
  s += '      return unsafe\n';
  s += '        .replace(/&/g, "\\x26amp;")\n';
  s += '        .replace(/</g, "\\x26lt;")\n';
  s += '        .replace(/>/g, "\\x26gt;")\n';
  s += '        .replace(/"/g, "\\x26quot;")\n';
  s += '        .replace(/\'/g, "\\x26apos;");\n';
  s += '    }\n';

  s += '    function appendUserMessage(text) {\n';
  s += '      const div = document.createElement("div");\n';
  s += '      div.className = "message user";\n';
  s += '      div.innerHTML = `<div class="msg-header-user">User</div><div class="msg-body">${escapeHtml(text).replace(/\\n/g, "<br>")}</div>`;\n';
  s += '      chatEl.appendChild(div);\n';
  s += '      chatEl.scrollTop = chatEl.scrollHeight;\n';
  s += '    }\n';

  s += '    function appendAssistantMessage(html, reasoningHtml) {\n';
  s += '      const div = document.createElement("div");\n';
  s += '      div.className = "message assistant";\n';
  s += '      \n';
  s += '      const bodyId = "msg-body-" + Date.now();\n';
  s += '      let inner = `<div class="msg-header">Spire</div>`;\n';
  s += '      if (reasoningHtml) {\n';
  s += '        const bubbleId = "res-" + Date.now();\n';
  s += '        inner += `<div class="reasoning-header" onclick="document.getElementById(\'${bubbleId}\').classList.toggle(\'visible\')">▶ Reasoning (click to toggle)</div>`;\n';
  s += '        inner += `<div id="${bubbleId}" class="reasoning-bubble">${reasoningHtml}</div>`;\n';
  s += '      }\n';
  s += '      inner += `<div class="msg-body-wrapper"><div class="msg-body" id="${bodyId}">${html}</div><button class="copy-btn" onclick="copyMsgBody(\'${bodyId}\')" title="Copy markdown">📋</button></div>`;\n';
  s += '      div.innerHTML = inner;\n';
  s += '      \n';
  s += '      chatEl.appendChild(div);\n';
  s += '      chatEl.scrollTop = chatEl.scrollHeight;\n';
  s += '    }\n';
  s += '\n';
  s += '    function copyMsgBody(bodyId) {\n';
  s += '      const bodyEl = document.getElementById(bodyId);\n';
  s += '      if (!bodyEl) return;\n';
  s += '      const text = bodyEl.innerText;\n';
  s += '      navigator.clipboard.writeText(text).then(() => {\n';
  s += '        const btn = bodyEl.parentElement.querySelector(".copy-btn");\n';
  s += '        if (btn) { btn.classList.add("copied"); btn.textContent = "\\u2713"; setTimeout(() => { btn.classList.remove("copied"); btn.textContent = "\\ud83d\\udccb"; }, 2000); }\n';
  s += '      }).catch(() => {});\n';
  s += '    }\n';

  s += '    function appendError(text) {\n';
  s += '      const div = document.createElement("div");\n';
  s += '      div.className = "error-message";\n';
  s += '      div.innerText = "Error: " + text;\n';
  s += '      chatEl.appendChild(div);\n';
  s += '      chatEl.scrollTop = chatEl.scrollHeight;\n';
  s += '    }\n';

  s += '    function clearChat() {\n';
  s += '      chatEl.innerHTML = "";\n';
  s += '    }\n';

  s += '    window.addEventListener("message", event => {\n';
  s += '      const msg = event.data;\n';
  s += '      switch (msg.type) {\n';
  s += '        case "response":\n';
  s += '          setWaiting(false);\n';
  s += '          appendAssistantMessage(msg.content, msg.reasoning);\n';
  s += '          break;\n';
  s += '        case "error":\n';
  s += '          setWaiting(false);\n';
  s += '          appendError(msg.content);\n';
  s += '          break;\n';
  s += '        case "clear":\n';
  s += '          clearChat();\n';
  s += '          break;\n';
  s += '        case "restoreConversation":\n';
  s += '          clearChat();\n';
  s += '          msg.messages.forEach(m => {\n';
  s += '             if(m.role === "user") appendUserMessage(m.content);\n';
  s += '             else appendAssistantMessage(m.content, m.reasoning ? escapeHtml(m.reasoning) : null);\n';
  s += '          });\n';
  s += '          break;\n';
  s += '        case "mcpUpdate":\n';
  s += '          document.getElementById("mcp-content").innerHTML = msg.html;\n';
  s += '          break;\n';
  s += '        case "switchTab":\n';
  s += '          const targetTab = msg.tab;\n';
  s += '          tabBtns.forEach(b => {\n';
  s += '            if (b.getAttribute("data-target") === "tab-" + targetTab) b.classList.add("active");\n';
  s += '            else b.classList.remove("active");\n';
  s += '          });\n';
  s += '          tabContents.forEach(c => {\n';
  s += '            if (c.id === "tab-" + targetTab) c.classList.add("active");\n';
  s += '            else c.classList.remove("active");\n';
  s += '          });\n';
  s += '          if (targetTab === "mcp") postMsg("mcp.refresh");\n';
  s += '          break;\n';
  s += '        case "statusUpdate":\n';
  s += '          updateThinkingStatus(msg.status);\n';
  s += '          break;\n';
  s += '      }\n';
  s += '    });\n';

  s += '    // Signal ready\n';
  s += '    postMsg("ready");\n';

  // ──────────────────────────────────────────────────────────────
  // GRAPH VISUALIZATION — Force-Directed Layout
  // ──────────────────────────────────────────────────────────────
  s += '    // ── Graph State ──\n';
  s += '    let graphData = { nodes: [], edges: [] };\n';
  s += '    let simNodes = [];\n';
  s += '    let simEdges = [];\n';
  s += '    let animFrame = null;\n';
  s += '    let isSimulating = false;\n';
  s += '    let selectedNodeId = null;\n';
  s += '    let zoomLevel = 1;\n';
  s += '    let panX = 0, panY = 0;\n';
  s += '    let isDragging = false, dragStartX, dragStartY;\n';
  s += '    let dragNode = null, dragNodeOffX, dragNodeOffY;\n';
  s += '    const svg = document.getElementById("graph-svg");\n';
  s += '    const container = document.getElementById("graph-container");\n';
  s += '    const tooltip = document.getElementById("graph-tooltip");\n';
  s += '    const legend = document.getElementById("graph-legend");\n';
  s += '    const NS = "http://www.w3.org/2000/svg";\n';
  s += '    const NODE_COLORS = {\n';
  s += '      entity: "#58a6ff", project: "#3fb950", conversation: "#d29922",\n';
  s += '      session: "#bc8cff", decision: "#f78166", blocker: "#f85149",\n';
  s += '      milestone: "#7ee787", standard: "#79c0ff", activeContext: "#ffa657",\n';
  s += '      default: "#8b949e"\n';
  s += '    };\n';
  s += '    const NODE_RADIUS = 8;\n';
  s += '    const REPULSION = 8000;\n';
  s += '    const ATTRACTION = 0.005;\n';
  s += '    const DAMPING = 0.85;\n';
  s += '    const CENTER_GRAVITY = 0.01;\n';
  s += '    const MAX_SPEED = 50;\n';
  s += '    const SETTLE_THRESHOLD = 0.5;\n';
  s += '    const MAX_ITERATIONS = 300;\n';
  s += '    let iteration = 0;\n';
  s += '    let settled = false;\n';
  s += '\n';
  s += '    function nodeColor(type) {\n';
  s += '      return NODE_COLORS[type] || NODE_COLORS.default;\n';
  s += '    }\n';
  s += '\n';
  s += '    function buildLegend() {\n';
  s += '      const types = Object.keys(NODE_COLORS).filter(k => k !== "default");\n';
  s += '      legend.innerHTML = types.map(t =>\n';
  s += '        `<span class="graph-legend-item"><span class="graph-legend-dot" style="background:${NODE_COLORS[t]}"></span>${t}</span>`\n';
  s += '      ).join("");\n';
  s += '    }\n';
  s += '    buildLegend();\n';
  s += '\n';
  s += '    function initSimulation(data) {\n';
  s += '      graphData = data;\n';
  s += '      if (!data || !data.nodes || data.nodes.length === 0) {\n';
  s += '        svg.innerHTML = "";\n';
  s += '        simNodes = [];\n';
  s += '        simEdges = [];\n';
  s += '        return;\n';
  s += '      }\n';
  s += '      const w = container.clientWidth || 600;\n';
  s += '      const h = container.clientHeight || 400;\n';
  s += '      simNodes = data.nodes.map((n, i) => ({\n';
  s += '        id: n.id, name: n.name, type: n.type, desc: n.description || "",\n';
  s += '        x: w/2 + (Math.random() - 0.5) * w * 0.5,\n';
  s += '        y: h/2 + (Math.random() - 0.5) * h * 0.5,\n';
  s += '        vx: 0, vy: 0, fx: 0, fy: 0, pinned: false\n';
  s += '      }));\n';
  s += '      const nodeMap = new Map(simNodes.map(n => [n.id, n]));\n';
  s += '      simEdges = data.edges.map(e => ({\n';
  s += '        source: nodeMap.get(e.from) || simNodes[0],\n';
  s += '        target: nodeMap.get(e.to) || simNodes[0],\n';
  s += '        type: e.type || "related"\n';
  s += '      })).filter(e => e.source && e.target);\n';
  s += '      iteration = 0;\n';
  s += '      settled = false;\n';
  s += '      isSimulating = true;\n';
  s += '      selectedNodeId = null;\n';
  s += '      zoomLevel = 1; panX = 0; panY = 0;\n';
  s += '      render();\n';
  s += '    }\n';
  s += '\n';
  s += '    function simulateStep() {\n';
  s += '      if (!isSimulating || settled || iteration >= MAX_ITERATIONS) {\n';
  s += '        isSimulating = false;\n';
  s += '        return;\n';
  s += '      }\n';
  s += '      iteration++;\n';
  s += '      const w = container.clientWidth || 600;\n';
  s += '      const h = container.clientHeight || 400;\n';
  s += '      const cx = w / 2, cy = h / 2;\n';
  s += '      // Reset forces\n';
  s += '      for (const n of simNodes) { n.fx = 0; n.fy = 0; }\n';
  s += '      // Repulsion (all pairs)\n';
  s += '      for (let i = 0; i < simNodes.length; i++) {\n';
  s += '        for (let j = i + 1; j < simNodes.length; j++) {\n';
  s += '          const a = simNodes[i], b = simNodes[j];\n';
  s += '          let dx = b.x - a.x, dy = b.y - a.y;\n';
  s += '          let dist = Math.sqrt(dx * dx + dy * dy) || 1;\n';
  s += '          let force = REPULSION / (dist * dist);\n';
  s += '          if (force > MAX_SPEED) force = MAX_SPEED;\n';
  s += '          a.fx -= (dx / dist) * force;\n';
  s += '          a.fy -= (dy / dist) * force;\n';
  s += '          b.fx += (dx / dist) * force;\n';
  s += '          b.fy += (dy / dist) * force;\n';
  s += '        }\n';
  s += '      }\n';
  s += '      // Attraction along edges\n';
  s += '      for (const e of simEdges) {\n';
  s += '        const a = e.source, b = e.target;\n';
  s += '        let dx = b.x - a.x, dy = b.y - a.y;\n';
  s += '        let dist = Math.sqrt(dx * dx + dy * dy) || 1;\n';
  s += '        let force = ATTRACTION * dist;\n';
  s += '        a.fx += (dx / dist) * force;\n';
  s += '        a.fy += (dy / dist) * force;\n';
  s += '        b.fx -= (dx / dist) * force;\n';
  s += '        b.fy -= (dy / dist) * force;\n';
  s += '      }\n';
  s += '      // Center gravity\n';
  s += '      for (const n of simNodes) {\n';
  s += '        n.fx += (cx - n.x) * CENTER_GRAVITY;\n';
  s += '        n.fy += (cy - n.y) * CENTER_GRAVITY;\n';
  s += '      }\n';
  s += '      // Apply forces\n';
  s += '      let totalEnergy = 0;\n';
  s += '      for (const n of simNodes) {\n';
  s += '        if (n.pinned) continue;\n';
  s += '        n.vx = (n.vx + n.fx) * DAMPING;\n';
  s += '        n.vy = (n.vy + n.fy) * DAMPING;\n';
  s += '        let speed = Math.sqrt(n.vx * n.vx + n.vy * n.vy);\n';
  s += '        if (speed > MAX_SPEED) {\n';
  s += '          n.vx = (n.vx / speed) * MAX_SPEED;\n';
  s += '          n.vy = (n.vy / speed) * MAX_SPEED;\n';
  s += '        }\n';
  s += '        n.x += n.vx;\n';
  s += '        n.y += n.vy;\n';
  s += '        totalEnergy += speed;\n';
  s += '      }\n';
  s += '      if (totalEnergy < SETTLE_THRESHOLD) settled = true;\n';
  s += '      render();\n';
  s += '    }\n';
  s += '\n';
  s += '    function render() {\n';
  s += '      const w = container.clientWidth || 600;\n';
  s += '      const h = container.clientHeight || 400;\n';
  s += '      svg.setAttribute("viewBox", "0 0 " + w + " " + h);\n';
  s += '      let html = "";\n';
  s += '      // Edges\n';
  s += '      for (const e of simEdges) {\n';
  s += '        const x1 = e.source.x, y1 = e.source.y;\n';
  s += '        const x2 = e.target.x, y2 = e.target.y;\n';
  s += '        const mx = (x1 + x2) / 2, my = (y1 + y2) / 2;\n';
  s += '        html += "<line class=\\"graph-edge\\" x1=\\"" + x1 + "\\" y1=\\"" + y1 + "\\" x2=\\"" + x2 + "\\" y2=\\"" + y2 + "\\"/>";\n';
  s += '        html += "<text class=\\"graph-edge-label\\" x=\\"" + mx + "\\" y=\\"" + (my - 4) + "\\">" + escapeHtml(e.type) + "</text>";\n';
  s += '      }\n';
  s += '      // Nodes\n';
  s += '      const filterVal = (document.getElementById("graph-search")?.value || "").toLowerCase();\n';
  s += '      for (const n of simNodes) {\n';
  s += '        const isSelected = n.id === selectedNodeId;\n';
  s += '        const matchesFilter = !filterVal || n.name.toLowerCase().includes(filterVal);\n';
  s += '        const opacity = (!selectedNodeId && !filterVal) ? 1 : (matchesFilter && (isSelected || !selectedNodeId)) ? 1 : 0.15;\n';
  s += '        const r = isSelected ? NODE_RADIUS + 4 : NODE_RADIUS;\n';
  s += '        const color = nodeColor(n.type);\n';
  s += '        html += "<g class=\\"graph-node\\" data-id=\\"" + n.id + "\\" opacity=\\"" + opacity + "\\">";\n';
  s += '        html += "<circle cx=\\"" + n.x + "\\" cy=\\"" + n.y + "\\" r=\\"" + r + "\\" fill=\\"" + color + "\\" stroke=\\"" + (isSelected ? "#fff" : "transparent") + "\\" stroke-width=\\"" + (isSelected ? 2 : 0) + "\\"/>";\n';
  s += '        html += "<text class=\\"graph-node-label\\" x=\\"" + n.x + "\\" y=\\"" + (n.y + r + 12) + "\\">" + escapeHtml(n.name) + "</text>";\n';
  s += '        html += "</g>";\n';
  s += '      }\n';
  s += '      svg.innerHTML = html;\n';
  s += '      // Attach event listeners\n';
  s += '      const nodeEls = svg.querySelectorAll(".graph-node");\n';
  s += '      for (const el of nodeEls) {\n';
  s += '        el.addEventListener("mouseenter", (e) => showTooltip(e, el.getAttribute("data-id")));\n';
  s += '        el.addEventListener("mousemove", (e) => moveTooltip(e));\n';
  s += '        el.addEventListener("mouseleave", hideTooltip);\n';
  s += '        el.addEventListener("click", (e) => { e.stopPropagation(); selectNode(el.getAttribute("data-id")); });\n';
  s += '        el.addEventListener("mousedown", (e) => { e.stopPropagation(); startNodeDrag(e, el.getAttribute("data-id")); });\n';
  s += '      }\n';
  s += '    }\n';
  s += '\n';
  s += '    function showTooltip(e, nodeId) {\n';
  s += '      const n = simNodes.find(s => s.id === nodeId);\n';
  s += '      if (!n) return;\n';
  s += '      tooltip.style.display = "block";\n';
  s += '      tooltip.innerHTML = "<div class=\\"tt-name\\">" + escapeHtml(n.name) + "</div>" +\n';
  s += '        (n.desc ? "<div class=\\"tt-desc\\">" + escapeHtml(n.desc.substring(0, 200)) + "</div>" : "") +\n';
  s += '        "<div class=\\"tt-type\\">type: " + escapeHtml(n.type) + "</div>";\n';
  s += '      moveTooltip(e);\n';
  s += '    }\n';
  s += '    function moveTooltip(e) {\n';
  s += '      const rect = container.getBoundingClientRect();\n';
  s += '      let x = e.clientX - rect.left + 12;\n';
  s += '      let y = e.clientY - rect.top - 10;\n';
  s += '      if (x + 260 > rect.width) x = e.clientX - rect.left - 260;\n';
  s += '      if (y < 0) y = 10;\n';
  s += '      tooltip.style.left = x + "px";\n';
  s += '      tooltip.style.top = y + "px";\n';
  s += '    }\n';
  s += '    function hideTooltip() { tooltip.style.display = "none"; }\n';
  s += '\n';
  s += '    function selectNode(nodeId) {\n';
  s += '      selectedNodeId = selectedNodeId === nodeId ? null : nodeId;\n';
  s += '      render();\n';
  s += '      showNodeDetail(nodeId);\n';
  s += '    }\n';
  s += '\n';
  s += '    function showNodeDetail(nodeId) {\n';
  s += '      const panel = document.getElementById("graph-detail-panel");\n';
  s += '      if (!nodeId || !panel) { panel.classList.remove("visible"); return; }\n';
  s += '      const n = graphData.nodes.find(n => n.id === nodeId);\n';
  s += '      if (!n) { panel.classList.remove("visible"); return; }\n';
  s += '      const color = nodeColor(n.type);\n';
  s += '      let html = "";\n';
  s += '      // Header\n';
  s += '      html += "<div class=\\"graph-detail-header\\">";\n';
  s += '      html += "<span class=\\"graph-detail-dot\\" style=\\"background:" + color + "\\"></span>";\n';
  s += '      html += "<span class=\\"graph-detail-title\\">" + escapeHtml(n.name) + "</span>";\n';
  s += '      html += "<button class=\\"graph-detail-close\\" onclick=\\"deselectNode()\\">\\u2716</button>";\n';
  s += '      html += "</div>";\n';
  s += '      // Type\n';
  s += '      html += "<div class=\\"graph-detail-section\\">";\n';
  s += '      html += "<div class=\\"graph-detail-label\\">Type</div>";\n';
  s += '      html += "<div class=\\"graph-detail-value\\">" + escapeHtml(n.type) + "</div>";\n';
  s += '      html += "</div>";\n';
  s += '      // Description\n';
  s += '      if (n.description) {\n';
  s += '        html += "<div class=\\"graph-detail-section\\">";\n';
  s += '        html += "<div class=\\"graph-detail-label\\">Description</div>";\n';
  s += '        html += "<div class=\\"graph-detail-value\\">" + escapeHtml(n.description) + "</div>";\n';
  s += '        html += "</div>";\n';
  s += '      }\n';
  s += '      // Properties\n';
  s += '      if (n.properties && Object.keys(n.properties).length > 0) {\n';
  s += '        html += "<div class=\\"graph-detail-section\\">";\n';
  s += '        html += "<div class=\\"graph-detail-label\\">Properties</div>";\n';
  s += '        html += "<table class=\\"graph-detail-table\\">";\n';
  s += '        for (const [key, val] of Object.entries(n.properties)) {\n';
  s += '          const displayVal = typeof val === "object" ? JSON.stringify(val) : String(val);\n';
  s += '          html += "<tr><td>" + escapeHtml(key) + "</td><td>" + escapeHtml(displayVal) + "</td></tr>";\n';
  s += '        }\n';
  s += '        html += "</table>";\n';
  s += '        html += "</div>";\n';
  s += '      }\n';
  s += '      panel.innerHTML = html;\n';
  s += '      panel.classList.add("visible");\n';
  s += '    }\n';
  s += '\n';
  s += '    function deselectNode() {\n';
  s += '      selectedNodeId = null;\n';
  s += '      document.getElementById("graph-detail-panel").classList.remove("visible");\n';
  s += '      render();\n';
  s += '    }\n';
  s += '\n';
  s += '    function filterGraph(val) {\n';
  s += '      selectedNodeId = null;\n';
  s += '      render();\n';
  s += '    }\n';
  s += '\n';
  s += '    function startNodeDrag(e, nodeId) {\n';
  s += '      const n = simNodes.find(s => s.id === nodeId);\n';
  s += '      if (!n) return;\n';
  s += '      dragNode = n;\n';
  s += '      dragNode.pinned = true;\n';
  s += '      const rect = svg.getBoundingClientRect();\n';
  s += '      dragNodeOffX = e.clientX - rect.left - n.x;\n';
  s += '      dragNodeOffY = e.clientY - rect.top - n.y;\n';
  s += '    }\n';
  s += '\n';
  s += '    // Canvas pan/drag\n';
  s += '    svg.addEventListener("mousedown", (e) => {\n';
  s += '      if (e.target === svg) {\n';
  s += '        isDragging = true;\n';
  s += '        dragStartX = e.clientX - panX;\n';
  s += '        dragStartY = e.clientY - panY;\n';
  s += '        if (selectedNodeId) deselectNode();\n';
  s += '      }\n';
  s += '    });\n';
  s += '    document.addEventListener("mousemove", (e) => {\n';
  s += '      if (dragNode) {\n';
  s += '        const rect = svg.getBoundingClientRect();\n';
  s += '        dragNode.x = e.clientX - rect.left - dragNodeOffX;\n';
  s += '        dragNode.y = e.clientY - rect.top - dragNodeOffY;\n';
  s += '        render();\n';
  s += '        return;\n';
  s += '      }\n';
  s += '      if (isDragging) {\n';
  s += '        panX = e.clientX - dragStartX;\n';
  s += '        panY = e.clientY - dragStartY;\n';
  s += '        svg.style.transform = "translate(" + panX + "px," + panY + "px) scale(" + zoomLevel + ")";\n';
  s += '        svg.style.transformOrigin = "0 0";\n';
  s += '      }\n';
  s += '    });\n';
  s += '    document.addEventListener("mouseup", () => {\n';
  s += '      isDragging = false;\n';
  s += '      if (dragNode) {\n';
  s += '        dragNode.pinned = false;\n';
  s += '        dragNode = null;\n';
  s += '        isSimulating = true;\n';
  s += '      }\n';
  s += '    });\n';
  s += '\n';
  s += '    // Zoom\n';
  s += '    svg.addEventListener("wheel", (e) => {\n';
  s += '      e.preventDefault();\n';
  s += '      const delta = e.deltaY > 0 ? 0.9 : 1.1;\n';
  s += '      zoomLevel = Math.min(Math.max(zoomLevel * delta, 0.1), 5);\n';
  s += '      svg.style.transform = "translate(" + panX + "px," + panY + "px) scale(" + zoomLevel + ")";\n';
  s += '      svg.style.transformOrigin = "0 0";\n';
  s += '    }, { passive: false });\n';
  s += '    function zoomIn() { zoomLevel = Math.min(zoomLevel * 1.3, 5); applyTransform(); }\n';
  s += '    function zoomOut() { zoomLevel = Math.max(zoomLevel * 0.7, 0.1); applyTransform(); }\n';
  s += '    function resetView() { zoomLevel = 1; panX = 0; panY = 0; applyTransform(); }\n';
  s += '    function applyTransform() {\n';
  s += '      svg.style.transform = "translate(" + panX + "px," + panY + "px) scale(" + zoomLevel + ")";\n';
  s += '      svg.style.transformOrigin = "0 0";\n';
  s += '    }\n';
  s += '\n';
  s += '    // Animation loop\n';
  s += '    function tick() {\n';
  s += '      if (isSimulating) {\n';
  s += '        simulateStep();\n';
  s += '        animFrame = requestAnimationFrame(tick);\n';
  s += '      }\n';
  s += '    }\n';
  s += '    function startSimulation() { if (!animFrame) animFrame = requestAnimationFrame(tick); }\n';
  s += '    function stopSimulation() { if (animFrame) { cancelAnimationFrame(animFrame); animFrame = null; } }\n';
  s += '\n';
  s += '    // Handle graph data from extension\n';
  s += '    window.addEventListener("message", event => {\n';
  s += '      const msg = event.data;\n';
  s += '      if (msg.type === "graph.data") {\n';
  s += '        stopSimulation();\n';
  s += '        initSimulation(msg.content);\n';
  s += '        startSimulation();\n';
  s += '      }\n';
  s += '    });\n';
  s += '\n';
  s += '    // Auto-refresh when switching to graph tab\n';
  s += '    tabBtns.forEach(btn => {\n';
  s += '      btn.addEventListener("click", () => {\n';
  s += '        if (btn.getAttribute("data-target") === "tab-graph") {\n';
  s += '          postMsg("graph.refresh");\n';
  s += '        }\n';
  s += '      });\n';
  s += '    });\n';
  
  s += '  </script>\n';
  s += '</body>\n';
  s += '</html>\n';
  
  return s;
}
